### PR TITLE
read dpa 

### PR DESCRIPTION
**Pull request by dvp2015**
The change adds handling DPA values from output. Besides, improves a bit setup.py and pytest modules, adds two more tests, fixes compatibility with the json schema: removes redundant hierarchy level for nuclides attribute. Recently merged with fispact/pypact master branch.

### CODE REVIEW

**Comment by thomasms** [comment]
This is good work. It's nice to have the schema validator. Thanks for contributing.

However, the build is failing with these changes. It appears that the command line tool 'fispactconverter.py' no longer works. Are you able to fix this?

Other comments:
- Pypact is on version 1.3.1 now, so I think we should match with this release.
- Why is the code duplicated in timestep.py at fispact_deserialize? For example the line is repeated (among others):
```python
            self.flux = get_value(starttag='* * * FLUX AMP IS', endtag='/cm^2/s')
```
- Whilst I acknowledge that the JSONSerializable bass class needs to be improved, only this should know about the 'json' module and acts as a facade. timestep.py now has the json dependency via 'import json' - is it possible to abstract this away somehow? 
- It seems that time is actual the delta time, I think it would be best renamed to delta_time, or alike, to avoid ambiguity.

**Comment by thomasms** [comment]
Thanks for rectifying some of the issues, it still seems that the build is failing for two reasons now:

- The fispactconverter tool no longer works, it may be because the CI is looking for `fispactconverter.py` instead of just `fispactconverter`. Either way this tool needs to work and documentation and CI must be updated to reflect changes.
- `python3 setup.py test` no longer works, developers need to be able to run this. I understand the code coverage is now better but devs should still be able to run the standard test.

Additionally, the version needs correcting. 

It may be worth separating these into two or more pull requests, since a lot has changed. This is good work, and much needed, but I think it would be better to track in separate items.
I have identified these significant updates:

- Improve code coverage, and produce a report
- Support for DPA
- Removal of `nuclides` duplication in JSON.
- Change of command line tool

Do you agree with these points?

**Comment by thomasms** [comment]
Sorry to be really pedantic, but the CI is failing for python 3.4, it seems this is due to line 37 in the setup.py.
```python
fispactconverter = pypact.tools.fispactconverter:main',
```
I am not sure why this no fails, but it did previously work, so we need to fix this.
If you can fix this then I can accept.

**Comment by dvp2015** [comment]
Excuse me for the late answer (as usually, to much to do).
I don't think the error is due to the entry-point spec: the travis CI log shows version conflict between pytest_runner and six modules.
I've tried the environment with python 3.4. The tests run fine, but "setup.py test" doesn't work: in my case due to version conflict of pytest_runner with setuptools. The "setup.py install" works,however.
Anyway the Python 3.4 is no longer supported (https://www.python.org/dev/peps/pep-0429/#id4):
"Release Schedule
Python 3.4 has now reached its end-of-life and has been retired. No more releases will be made."

Also my Pycharm IDE  doesn't support Python 3.4: end-of-life date reached.
Do you really need to support Python 3.4?

**Comment by dvp2015** [comment]
The fispact/pypact master is merged to branch dvp2015/read_dpa (for printlib5 commit). All tests passed locally. Removed python 3.4 spec from .travis.yml because it's been reached "end-of-life date".

**Comment by thomasms** [comment]
OK, whilst I think we should still support python 3.4 (I am sure we still have some users on this version), I acknowledge that it is a rather small group and only affects the tests. I appreciate all your work and will accept this now. 
Thank you.

**Pull request merged**
